### PR TITLE
add sparkthink tap to singer index

### PR DESCRIPTION
**Pull request by jtimeus-slalom**
We've created tap-sparkthink to hit the Sparkthink GraphQL endpoint and are ready to build pipelines using it
Adding it to singer index so that the tapdance docker image build process will create an image for the pipeline to use
We also included a reference to tap-dbt as that is a near term future project for us

### CODE REVIEW

**Review by aaronsteers — APPROVED** [review]
Looks good to me! :shipit:

**Comment by jtimeus-slalom** [comment]
SparkThink team is adding pagination to their GraphQL endpoint in prod within the next week.  We'd like to update tap-sparkthink to handle pagination when that feature is ready, so will leave this code complete PR open until tap-sparkthink is updated.  The when tap-sparkthink has the correct pagination behavior, we'll close the PR so the "prod" docker images include the pagination feature

**Comment by aaronsteers** [comment]
@jtimeus-slalom - I somehow missed the message to "merge when ready". Is this ready to go? I'm happy to merge. 

Also - are you able to manually invoke the pipeline from the Actions tab if needed to rebuild images?

**Comment by aaronsteers** [comment]
Also - what do you think of us listing "Slalom SparkThink" on MeltanoHub 😄: https://hub.meltano.com/singer/taps/

Even if internally you are running with Meltano, you could direct clients/partners to the hosted documentation there, and they can use Meltano or another Singer runner to extract data.

**Comment by jtimeus-slalom** [comment]
@aaronsteers We have 1 more change to tap-sparkthink that is being tested now, so we've been leaving the PR open to be able to regenerate docker images

I do not see an option to Invoke a pipeline on the Actions tab, that would be what we are looking for.  If we can't just run the docker step and skip the pypi publish step it would work right now, otherwise we could add an additional job that just does the docker step.

How would I go about getting the ability to Invoke pipelines?

**Comment by jtimeus-slalom** [comment]
I think it would be great if "Slalom SparkThink" showed up on Meltano Hub.  We haven't prioritized making the documentation anything special, but the tap is going to be running in our prod every day so will be high quality if clients want to use it

**Pull request merged**
